### ISSUE TITLE
threadPause support?

### ISSUE THREAD

**Issue by zyofeng** [abstracta/jmeter-dotnet-dsl#10]
Looks like this is not supported in dotnet version yet?

**Comment by rabelenda** [comment]
Hello, thanks for asking. Yes, currently there is no api in dotnet as it is in java, but it should be easy to add. We will consider it for next release.

**Comment by rabelenda** [comment]
We recently released a [new version](https://github.com/abstracta/jmeter-dotnet-dsl/releases/tag/v0.6) which includes ThreadPause. I am closing this ticket, but feel free to re open it.
