### ISSUE TITLE
Missing allow quoted data in DslCsvDataSet

### ISSUE THREAD

**Issue by SeanLS** [abstracta/jmeter-dotnet-dsl#14]
### Issue
When using CSV data which then contains JSON data and with a different type of delimiter (specifying \n or other types as a delimter) the JMeter DSL runner fails to run and reads the data as <EOF>

Sample JSON CSV data
--------------------------
HeaderValue
[{ "keyValue1" : "dataValue1"}]
[{ "keyValue2" : "dataValue2"}]
[{ "keyValue3" : "dataValue3"}]

Url to pass values into:
https://fakeurl.com/testing/
Body: ${HeaderValue}

------ Current behaviour -----
Url: https://fakeurl.com/testing/
Body: '< EOF >'

----Expected behaviour----
Url: https://fakeurl.com/testing/
Body: [{ "keyValue1" : "dataValue1"}]

Url: https://fakeurl.com/testing/
Body: [{ "keyValue2" : "dataValue2"}]

etc....

### Additional information 
Option is avaliable in Jmeter. Please see screenshot below.
- https://jmeter.apache.org/images/screenshots/csvdatasetconfig.png

Please add the "**_Allow quoted data?_**" flag to the .Net configuration.

### Notes
Love the library and the simplification for .Net yet with this feature missing it makes it very difficult to post preconfigured JSON test data to an endpoint. Other alternatives is having a "fixed" JSON payload in the body section, which does work, yet you loose the dynamic data insertion for a steadyload and rampup of changing datra for a given endpoint that may be configured to take multiple JSON inputs.

**Comment by rabelenda** [comment]
Hello, thank you for trying and asking about this and providing so well formatted report.

Currently the `CsvDataSet` element already sets allow quoted data to true. This was done to standarize the formatting of CSV files regardless if random order is required or not (random order uses Blazemeter plugin which contains Random CSV Data Set Config element, and such element does not provide a setting to disable such behavior).

In your case you can adapt the csv by enclosing with quotes and replacing each quote with double quotes (a standard CSV format for quoted values). Eg:

```csv
HeaderValue
"[{ ""keyValue1"" : ""dataValue1""}]
"[{ ""keyValue2"" : ""dataValue2""}]
"[{ ""keyValue3"" : ""dataValue3""}]
```

Do you think that with such workaround is still required to add support for the "unquoted" option? That would require extending the BM plugin to support the unquoted case)?

**Comment by SeanLS** [comment]
I will try your suggestion tomorrow and feedback to you. Adding this in the CSV docs section may help others as well should it work.

**Comment by SeanLS** [comment]
@rabelenda - While thinking about your suggestion, I think the Allow Quoted data should be allowed as your suggestion means that the payload is not conforming to the JSON standard. This requires re-working of any JSON data to have an invalid JSON payload which is means you are diverging from standards.

While I appreciate that you are trying to standardise things, sticking to the standards for a given language should be a priority. 

Additional examples.... If you are posting XML, HTML, JS, etc directly you should have the ability to send the data verbatim for that given row in a CSV. Exactly like producer and consumer would act and form/produce/send the markup for each request.
