### ISSUE TITLE
Assertion missing Average option

### ISSUE THREAD

**Issue by SeanLS** [abstracta/jmeter-dotnet-dsl#16]
The test assertion has configuration for errors and 95% percentile yet it seems to be missing the other configuration option such as:
 - Average

See screenshot from JMeter
- https://jmeter.apache.org/images/screenshots/aggregate_graph.png

Could you please add in the "**_Average_**" configuration?

**Comment by rabelenda** [comment]
Hello, have you checked the Mean property?

We might add some Average alias property in the future to avoid confusions.

**Comment by SeanLS** [comment]
I have not used the mean property as it not inline owth our expectations. Adding the Average would be much appreciated. Thank you for reviewing.

**Comment by rabelenda** [comment]
Sorry, I didn't understand why are not using the mean property. Can you clarify? Did you mean that you didn't expect Mean property to actually contain the Average?

**Comment by SeanLS** [comment]
@rabelenda - There is no option to utalise the Mean option as well as the other various stats as part opf the resultt. The code ion the following section should be expanded:
- https://github.com/abstracta/jmeter-dotnet-dsl/blob/main/Abstracta.JmeterDsl/Core/Stats/StatsSummary.cs

**Comment by rabelenda** [comment]
I am closing this issue seems it seems as there is no need to implement a new feature for this. We might consider in the future adding some alias to Mean to avoid confusion. Feel free to re open it if you consider it not closed.

**Comment by SeanLS** [comment]
You are adding a wrapper round JMeter. It is up to the implementors on how they would like to implement the features and as such you should expose all the available features in JMeter.

**Comment by rabelenda** [comment]
But the feature is already exposed. Have you checked the api Mean method that I already described?

Eg: `stats.Overall.SampleTime.Mean`
