### ISSUE TITLE
 Incorporate functionality to verify the expected response.

### ISSUE THREAD

**Issue by BKWonder12** [abstracta/jmeter-dotnet-dsl#9]
Hello Team 
 I have a substantial scenarios where I need to execute multiple POST, GET, and PUT requests. I've observed that in JMeter Java-based, we can assert both the response and JSON response.

- https://abstracta.github.io/jmeter-java-dsl/guide/#json-extraction
- https://abstracta.github.io/jmeter-java-dsl/guide/#check-for-expected-response

Please below sample tests 
`

        private const string BaseUrl = "https://your-api.com";

        [Test]
        public void ClientCredentialsFlowLoadTests()
        {

            var stats = TestPlan(
                CsvDataSet("users.csv"),
                HttpCookies().Disable(),
                HttpCache().Disable(),
                ThreadGroup(3, 10,
                    HttpSampler("Client Credentials Flow", BaseUrl)
                        .Method(HttpMethod.Post.Method)
                        .ContentType(new System.Net.Http.Headers.MediaTypeHeaderValue(MediaTypeNames.Application.FormUrlEncoded))
                        .Param("grant_type", "client_credentials")
                        .Param("client_id", "${clientId}")
                        .Param("client_secret", "${clientSecret}")
                        .Param("scope", "${scope}")
                ).Children(
                        RegexExtractor("ACCESS_TOKEN", "accessToken=(.*)")
                    ),
                 ResponseFileSaver(DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss").Replace(":", "-") + "-response")
            ).Run();

            Assert.That(stats.Overall.SampleTimePercentile99, Is.LessThan(TimeSpan.FromSeconds(20)));
        }
    

`

**Within my code, I aim to:**

1. Validate the response status.
2. Retrieve my access token and validate its contents.
3. Although unrelated to the aforementioned code, I have additional scenarios where I intend to introduce pauses between requests, as illustrated in this resource: https://abstracta.github.io/jmeter-java-dsl/guide/#emulate-user-delays-between-requests

**Comment by rabelenda** [comment]
Excelent! Thank you bringing this here! We will consider it for the next release.

**Comment by rabelenda** [comment]
Hello, we recently released [a new version](https://github.com/abstracta/jmeter-dotnet-dsl/releases/tag/v0.6) which includes `ResponseAssertion` and different timers. Let us know of any comments. I will close this issue, feel free to re open it.
